### ISSUE TITLE
Not able to instal with Laravel 6 package

### ISSUE THREAD

**Issue by ted81das** [Mnikoei/laravel-keycloak-admin#2]
composer require mnikoei/laravel-keycloak-admin
Using version dev-master for mnikoei/laravel-keycloak-admin
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for mnikoei/laravel-keycloak-admin dev-master -> satisfiable by mnikoei/laravel-keycloak-admin[dev-master].
    - Conclusion: remove guzzlehttp/guzzle 6.5.5
    - Conclusion: don't install guzzlehttp/guzzle 6.5.5
    - mnikoei/laravel-keycloak-admin dev-master requires guzzlehttp/guzzle ^7.0 -> satisfiable by guzzlehttp/guzzle[7.0.0, 7.0.0-beta.1, 7.0.0-beta.2, 7.0.0-rc.1, 7.0.1, 7.0.x-dev, 7.1.0, 7.1.1, 7.2.0, 7.1.x-dev].
    - Can only install one of: guzzlehttp/guzzle[7.0.0, 6.5.5].
    - Can only install one of: guzzlehttp/guzzle[7.0.0-beta.1, 6.5.5].
    - Can only install one of: guzzlehttp/guzzle[7.0.0-beta.2, 6.5.5].
    - Can only install one of: guzzlehttp/guzzle[7.0.0-rc.1, 6.5.5].
    - Can only install one of: guzzlehttp/guzzle[7.0.1, 6.5.5].
    - Can only install one of: guzzlehttp/guzzle[7.0.x-dev, 6.5.5].
    - Can only install one of: guzzlehttp/guzzle[7.1.0, 6.5.5].
    - Can only install one of: guzzlehttp/guzzle[7.1.1, 6.5.5].
    - Can only install one of: guzzlehttp/guzzle[7.2.0, 6.5.5].
    - Can only install one of: guzzlehttp/guzzle[7.1.x-dev, 6.5.5].
    - Installation request for guzzlehttp/guzzle (locked at 6.5.5) -> satisfiable by guzzlehttp/guzzle[6.5.5].

Installation failed, reverting ./composer.json to its original content.

**Comment by haizad** [comment]
Check the previous commit of this project. It works for Laravel 6.

**Comment by Mnikoei** [comment]
It is compatible now.
