### ISSUE TITLE
ErrorException: Array to string conversion

### ISSUE THREAD

**Issue by haizad** [Mnikoei/laravel-keycloak-admin#3]
Hi, would you mind to look on this error message?

```
ErrorException: Array to string conversion in file D:\project\vendor\mnikoei\laravel-keycloak-admin\src\Services\Service.php on line 73
```

I was trying to send request to the Keycloak using following script.
```
use Mnikoei\Facades\KeycloakAdmin;

...

keycloakAdmin::user()->create([
      
     'body' => [  // https://www.keycloak.org/docs-api/7.0/rest-api/index.html#_userrepresentation
             
             'username' => 'foo'
              
       ]

]);

```

Thanks!

**Comment by haizad** [comment]
I solved it by creating new array, then convert into json.
```
$array = array(
            'query' => array(
              "email" => 'email@email.com')
          ) ;
$response = json_encode($array);
KeycloakAdmin::user()->all($response);
```

**Comment by haizad** [comment]
It doesn't work....

**Comment by haizad** [comment]
Please look on the laravel-keycloak-admin\src\Services\Service.php

**Comment by haizad** [comment]
Please add back on the laravel-keycloak-admin\src\Services\Service.php
```
if(is_string($value)){
     $api = str_replace('{'.$name.'}', $value, $api);
}
```

**Comment by abhiways** [comment]
Updating haizat's answer
Line 73 to 76
/laravel-keycloak-admin/src/Services/Service.php

` foreach($values as $name => $value) {
            if(!is_array($value)) {
            $api = str_replace('{'.$name.'}', $value, $api);
        }`
